= 01-microproject-MichaelTran6624
Michael Tran
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
//ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Klassendiagramm

[plantuml]
----
include::plantuml/cld.puml[]
----

== Beschreibung

Die Anwendung ist eine Webseite, wo Kunden (Customer) einen Tisch (Table) reservieren können. Der Kunde registriert sich mit Namen und gibt bei der Reservierung das Datum an. Außderdem können Kunden ihre Reservierung abrufen oder die Reservierung stonieren.

== Technologien

=== GraphQL

==== Was ist GraphQL?
GraphQL ist eine Abfrage Sprache für API's und eine die zur Laufzeit diese Abfragen mit den vorhandenen Daten verwendet.

==== Alternativen für GraphQL
* REST

==== Verwendung im Microprojekt

CustomerResource.java
[source, java]
----
//
//
    @Mutation
    public Customer addCustomer(Customer customer) {
        return customerRepository.saveCustomer(customer);
    }

    @Mutation
    public Table addTable(Table table){
        return tableRepository.saveTable(table);
    }

    @Mutation
    public Reservation addReservation(Reservation reservation) {
        return reservationRepository.saveReservation(reservation);
    }
//
//
----
* HTTP-Abfrage
[source, http request]
----
###POST Customer

POST http://localhost:8080/api/graphql
Content-Type: application/graphql

mutation addNewCustomer{
  addCustomer(customer: {
    firstName: "Max",
    lastName: "Muster"
  	}
  )
  {
    firstName
    lastName
  }
}

###POST Table

POST http://localhost:8080/api/graphql
Content-Type: application/graphql

mutation addNewTable {
  addTable(table: {
    tableNr: "1L",
    seats: 3
  	}
  )
  {
    tableNr
    seats
  }
}

### POST Reservation

POST http://localhost:8080/api/graphql
Content-Type: application/graphql

mutation addNewReservation{
  addReservation(reservation: {
		customer: {
      firstName: "Max"
      lastName: "Muster"
    },
    reservationTable: {
      tableNr: "1L"
      seats: 3
    },
    reservationDate: "2022-01-04"
  	}
  )
  {
    customer{
      firstName
      lastName
    }
    reservationTable{
      tableNr
      seats
    }
    reservationDate
  }
}
----

=== Validation

Customer.java
[source, java]
----
//
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "CU_FIRSTNAME")
    @Size(message = "Firstname length has to be between 2 and 40", min = 2, max = 40)
    @NotBlank(message = "Firstname cannot be empty")
    String firstName;

    @Column(name = "CU_LASTNAME")
    @Size(message = "Lastname length has to be between 2 and 40", min = 2, max = 40)
    @NotBlank(message = "Lastname cannot be empty")
    String lastName;
//
----

Table.java
[source, java]
----
//
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @Column(name = "TA_TABLENR")
    @NotBlank(message = "TableNr cannot be empty")
    String tableNr;

    @Column(name = "TA_SEATS")
    @NotBlank(message = "Seats cannot be empty")
    @Min(message = "Seats have to be greater than 1", value = 1)
    int seats;
//
----

Reservation.java
[source, java]
----
//
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @Column(name = "RE_RESERVATIONDATE")
    @NotBlank(message = "Date cannot be empty")
    LocalDate reservationDate;

    @NotBlank(message = "Customer cannot be empty")
    @ManyToOne(cascade = CascadeType.ALL)
    Customer customer;

    @NotBlank(message = "Reservationtable cannot be empty")
    @ManyToOne(cascade = CascadeType.ALL)
    Table reservationTable;
//
----

=== Qute
==== Was ist Qute?
Qute ist eine Templating-Engine, die speziell für die Bedürfnisse von Quarkus entwickelt wurde.

==== Alternative
* Angular

==== Verwendung im Mikroprojekt

CustomerResource.java
[source, java]
----
//
    @CheckedTemplate
    public static class Templates {
        public static native TemplateInstance customers(Customer customer);
        public static native TemplateInstance tables(Table table);
        public static native TemplateInstance reservations(Reservation reservation);
    }
//
    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("/html/customer/{id}")
    public TemplateInstance getCustomerHTML(@PathParam("id") Long id) {
        return Templates.customers(customerRepository.findById(id));
    }

    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("/html/table/{id}")
    public TemplateInstance getTableHTML(@PathParam("id") Long id) {
        return Templates.tables(tableRepository.findById(id));
    }

    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("/html/reservation/{id}")
    public TemplateInstance getReservationHTML(@PathParam("id") Long id) {
        return Templates.reservations(reservationRepository.findById(id));
    }
//
----

customer.html
[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CustomerID {customer.id}</title>
</head>
<body>
    <p>Firstname: {customer.firstName}</p>
    <p>Lastname: {customer.lastName}</p>
</body>
</html>
----
reservation.html
[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ReservationID {reservation.id}</title>
</head>
<body>
    <p>Reservationdate: {reservation.reservationDate}</p>
    <p>Table: {reservation.reservationTable}</p>
    <p>Customer: {reservation.customer}</p>
</body>
</html>
----

tables.html
[source, html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TableID {table.id}</title>
</head>
<body>
    <p>TableNr: {table.tableNr}</p>
    <p>Seats: {table.seats}</p>
</body>
</html>
----