= 01-microproject-MichaelTran6624
Michael Tran
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
//ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Klassendiagramm

[plantuml]
----
include::plantuml/cld.puml[]
----

== Beschreibung

Die Anwendung ist eine Webseite, wo Kunden (Customer) einen Tisch (Table) reservieren können. Der Kunde registriert sich mit Namen und gibt bei der Reservierung das Datum an. Außderdem können Kunden ihre Reservierung abrufen oder die Reservierung stonieren.

== Technologien

=== GraphQL

==== Was ist GraphQL?
GraphQL ist eine Abfrage Sprache für API's und eine die zur Laufzeit diese Abfragen mit den vorhandenen Daten verwendet.

==== Alternativen für GraphQL
* REST

==== Verwendung im Microprojekt

CustomerResource.java
[source, java]
----
//
//
    @Mutation
    public Customer addCustomer(Customer customer) {
        return customerRepository.saveCustomer(customer);
    }

    @Mutation
    public Table addTable(Table table){
        return tableRepository.saveTable(table);
    }

    @Mutation
    public Reservation addReservation(Reservation reservation) {
        return reservationRepository.saveReservation(reservation);
    }
//
//
----
* HTTP-Abfrage
[source, http request]
----
###POST Customer

POST http://localhost:8080/api/graphql
Content-Type: application/graphql

mutation addNewCustomer{
  addCustomer(customer: {
    firstName: "Max",
    lastName: "Muster"
  	}
  )
  {
    firstName
    lastName
  }
}

###POST Table

POST http://localhost:8080/api/graphql
Content-Type: application/graphql

mutation addNewTable {
  addTable(table: {
    tableNr: "1L",
    seats: 3
  	}
  )
  {
    tableNr
    seats
  }
}

### POST Reservation

POST http://localhost:8080/api/graphql
Content-Type: application/graphql

mutation addNewReservation{
  addReservation(reservation: {
		customer: {
      firstName: "Max"
      lastName: "Muster"
    },
    reservationTable: {
      tableNr: "1L"
      seats: 3
    },
    reservationDate: "2022-01-04"
  	}
  )
  {
    customer{
      firstName
      lastName
    }
    reservationTable{
      tableNr
      seats
    }
    reservationDate
  }
}
----

=== Validation

Customer.java
[source, java]
----
/*
...
*/
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "CU_FIRSTNAME")
    @Size(message = "Firstname length has to be between 2 and 40", min = 2, max = 40)
    @NotBlank(message = "Firstname cannot be empty")
    String firstName;

    @Column(name = "CU_LASTNAME")
    @Size(message = "Lastname length has to be between 2 and 40", min = 2, max = 40)
    @NotBlank(message = "Lastname cannot be empty")
    String lastName;
/*
...
*/
----

Table.java
[source, java]
----
/*
...
*/
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @Column(name = "TA_TABLENR")
    @NotBlank(message = "TableNr cannot be empty")
    String tableNr;

    @Column(name = "TA_SEATS")
    @NotBlank(message = "Seats cannot be empty")
    @Min(message = "Seats have to be greater than 1", value = 1)
    int seats;
/*
...
*/
----

Reservation.java
[source, java]
----
/*
...
*/
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @Column(name = "RE_RESERVATIONDATE")
    @NotBlank(message = "Date cannot be empty")
    LocalDate reservationDate;

    @NotBlank(message = "Customer cannot be empty")
    @ManyToOne(cascade = CascadeType.ALL)
    Customer customer;

    @NotBlank(message = "Reservationtable cannot be empty")
    @ManyToOne(cascade = CascadeType.ALL)
    Table reservationTable;
/*
...
*/
----

=== Qute
==== Was ist Qute?
Qute ist eine Templating-Engine, die speziell für die Bedürfnisse von Quarkus entwickelt wurde.

==== Alternative
* Angular

==== Verwendung im Mikroprojekt

CustomerResource.java
[source, java]
----
/*
...
*/
    @CheckedTemplate
    public static class Templates {
        public static native TemplateInstance customers(Customer customer);
        public static native TemplateInstance tables(Table table);
        public static native TemplateInstance reservations(Reservation reservation);
    }
/*
...
*/
    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("/html/customer/{id}")
    public TemplateInstance getCustomerHTML(@PathParam("id") Long id) {
        return Templates.customers(customerRepository.findById(id));
    }

    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("/html/table/{id}")
    public TemplateInstance getTableHTML(@PathParam("id") Long id) {
        return Templates.tables(tableRepository.findById(id));
    }

    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("/html/reservation/{id}")
    public TemplateInstance getReservationHTML(@PathParam("id") Long id) {
        return Templates.reservations(reservationRepository.findById(id));
    }
/*
...
*/
----

customer.html
[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CustomerID {customer.id}</title>
</head>
<body>
    <p>Firstname: {customer.firstName}</p>
    <p>Lastname: {customer.lastName}</p>
</body>
</html>
----
reservation.html
[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ReservationID {reservation.id}</title>
</head>
<body>
    <p>Reservationdate: {reservation.reservationDate}</p>
    <p>Table: {reservation.reservationTable}</p>
    <p>Customer: {reservation.customer}</p>
</body>
</html>
----

tables.html
[source, html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TableID {table.id}</title>
</head>
<body>
    <p>TableNr: {table.tableNr}</p>
    <p>Seats: {table.seats}</p>
</body>
</html>
----

=== gRPC

==== Was ist gRPC?
gRPC ist ein Remote Procedure Call Framework, welches Aufrufe von Funktionen in anderen Addressräumen zulässt.

==== Was wird gelöst?
Ein Programm kann den Dienst eines anderen Programmes verwenden, die nicht im selben Netzwerk sind.

==== Verwendung im Mikroprojekt
helloworld.proto
[source, prototext]
----
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.quarkus.example";
option java_outer_classname = "HelloWorldProto";

package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
----

HelloService.java
[source, java]
----
package at.htl.restrauntmanagement.boundary;

import io.quarkus.example.Greeter;
import io.quarkus.example.HelloReply;
import io.quarkus.example.HelloRequest;
import io.quarkus.grpc.GrpcService;
import io.smallrye.mutiny.Uni;

@GrpcService
public class HelloService implements Greeter {

    @Override
    public Uni<HelloReply> sayHello(HelloRequest request) {
        return Uni.createFrom().item(() ->
                HelloReply.newBuilder().setMessage("Hello " + request.getName() + "!").build()
        );
    }
}
----

CustomerResource.java
[source, java]
----
/*
...
*/
    @GrpcClient
    Greeter hello;
/*
...
*/
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/greet/{name}")
    public Uni<String> greetCustomer(@PathParam("name") String name){
        return hello.sayHello(HelloRequest.newBuilder().setName(name).build())
                .onItem().transform(helloReply -> helloReply.getMessage());
    }
----

=== Security with JPA

==== Was ist das Problem?

Eine Quarkus Applikation ist nicht geschützt. Um sie zu schützen verwenden wir
eine der Möglichkeiten die Applikation zu schützen mit JPA.

==== Alternativen eine Quarkus-Applikation zu schützen
* Security with .properties files
* Security with JDBC
* Security with LDAP
* ...

==== Verwendung im Mikroprojekt

Customer.java
[source, java]
----
@UserDefinition // <.>
public class Customer {
...

    @Column(name = "CU_USERNAME")
    @NotBlank(message = "Username cannot be empty")
    @Username // <.>
    String username;

    @Column(name = "CU_PASSWORD")
    @NotBlank(message = "Password cannot be empty")
    @Password // <.>
    String password;

    @Column(name = "CU_ROLE")
    @NotBlank(message = "Role cannot be empty")
    @Roles // <.>
    String role;

...

    public Customer(String firstName, String lastName, String username, String password, String role) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.password = password;
        this.role = role;
    }

...

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

...
----

<.> `@UserDefinition` - Annotiation darf nur in einer Entity sein. Die Verwendung von `security-jpa` - extension wird verwendet.
<.> das Feld ist der Username
<.> das Feld ist das Passwort
<.> das Feld ist die Rolle

CustomerResource.java
[source, java, highlight=3;12]
----
...

    @PermitAll
    @Mutation // <.>
    public Customer addCustomer(Customer customer) {
        return customerRepository.saveCustomer(customer);
    }

...

    @GET // <.>
    @RolesAllowed("customer")
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/greet/{name}")
    public Uni<String> greetCustomer(@PathParam("name") String name){
        return hello.sayHello(HelloRequest.newBuilder().setName(name).build())
                .onItem().transform(helloReply -> helloReply.getMessage());
    }

...
----

Es werden Rechte auf die jeweiligen Methoden verteilt.

<.> in der Methode können alle Benutzer zugreifen
<.> in der Methode können nur Benutzer mit der Rolle `customer` zugreifen